### ISSUE TITLE
Fix HDF layer conversion to GeoTIFF

### ISSUE THREAD

**Issue by mbjoseph** [NateMietk/modis-burned-area#1]
Currently we cannot convert HDF subdatasets to GeoTIFFs, because the gdalUtils package seems to be unable to find the gdal installation. 

Relevant lines here: 

https://github.com/NateMietk/unpack-hdf-and-make-burn-date/blob/master/src/make_burn_date_from_web.R#L87

Possible fixes:

1. Figure out how to point gdalUtils to the gdal installation in the r-spatial-aws Docker container

2. Use the MODIS R package to identify subdatasets

3. Manually construct paths to these subdatasets

**Comment by admahood** [comment]
I just checked out the MODIS library in R. looks like you need gdal version
>2.0, which my linux didn't have and I had to do a bunch of dilly-dallying
around to fix. but now it works! so we'll have to check if the docker image
has the >2.0 gdal
