### ISSUE TITLE
Cleaning and organizing

### ISSUE THREAD

**Issue by NateMietk** [NateMietk/modis-burned-area#6]
Hey @admahood ,

We need to organize these scripts and start naming them in a more conventional way.  Can you go through the scripts you made, delete the ones that are redundant and mark them in the order they need to be ran?  For instance, there are 3 confusion matrix scripts.  This repo is getting confusing.  I am going to update all the codes in the MODISr package to reflect the changes we made. That should clean things up big time too.

Thanks!

**Comment by admahood** [comment]
all done
